name: agents
description: Voice-powered AI agents made easy. Official Agents SDK for Flutter by PlayAI. The plugin supports iOS, Android, and Web platforms.
version: 0.0.1-alpha.1
homepage: https://play.ai/
repository: https://github.com/playht/agents-flutter/
issue_tracker: https://github.com/playht/agents-flutter/issues
documentation: https://docs.play.ai/documentation/client-sdks/flutter-sdk

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.10.0"

platforms:
  android:
  ios:
  web:

dependencies:
  audio_session: ^0.1.25
  flutter:
    sdk: flutter
  flutter_sound: ^9.26.0
  logger: ^2.5.0
  permission_handler: ^11.4.0
  vad: ^0.0.5
  web_socket_channel: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

topics:
  - ai
  - ai-agents
  - voice-agents
  - vad
  - voice-activity-detection
  - text-to-speech
  - speech-recognition
  - voice-cloning
  - voice-conversion
  - voice-generation
  - voice-embedding
  - voice-detection
  - voice-recognition
